name: metadata_fetch
description: A dart library for extracting metadata on web pages such as OpenGraph, Meta, and Structured Data
version: 1.1.0
homepage: https://github.com/gabdsg/metadata_fetch

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  http: ^1.2.2
  string_validator: ^1.1.0
  html: ^0.15.4

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.25.8
